language: python
python: 3.5
services:
  - postgresql
env:
  global:
    - PLAYGROUND_ROOT=$TRAVIS_BUILD_DIR
    - PYTHONPATH="$PLAYGROUND_ROOT:$PYTHONPATH"
    - PLAYGROUND_APP_ENV=test
  matrix:
    - PLAYGROUND_USE_SQLITE=yes
    - >
      PLAYGROUND_DATABASE_HOST=localhost
      PLAYGROUND_DATABASE_PORT=5432
      PLAYGROUND_DATABASE_USER=postgres
install: bash scripts/playground-pip-install
script:
  - flake8
  - py.test
